apiVersion: apps/v1beta1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: jenkins-adapter-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        application: jenkins-adapter-v1
        version: v1
    spec:
      containers:
      - name: jenkins-adapter-v1
        image: consortit-docker-cme-local.jfrog.io/jenkins-adapter:image-version
        ports:
        - containerPort: 8080
        - containerPort: 8081
        env:
        - name: JENKINS_USER
          valueFrom:
            secretKeyRef:
              name: jenkins-adapter-secret
              key: JENKINS_USER
        - name: JENKINS_PWD
          valueFrom:
            secretKeyRef:
              name: jenkins-adapter-secret
              key: JENKINS_PWD
        - name: JENKINS_URL
          value: "https://jenkins.consort-it.de"
        - name: jwk_url
          value: "https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_M4FyC0JPA/.well-known/jwks.json"
        - name: jwk_kid
          value: "ImJm862bLPCtlhQQy368BAoKPayD9DLpNwywW2fhZPI="
        - name: jwk_alg
          value: "RS256"
      imagePullSecrets:
        - name: regsecret
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-adapter-v1
  labels:
    application: jenkins-adapter-v1
    version: v1
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      name: external
  selector:
    application: jenkins-adapter-v1
    version: v1
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins-adapter-v1
  labels:
    application: jenkins-adapter-v1
spec:
  rules:
  - host: "cme.dev.k8s.consort-it.de"
    http:
      paths:
      - path: /api/v1/jenkins-adapter
        backend:
          serviceName: jenkins-adapter-v1
          servicePort: 80